config/routes.rb
Rails.application.routes.draw do



  resources :users

  resources :microposts do
    resources :comments
  end
  resources :notifications

  resources :photos do
    resources :comments
  end

  resources :comments

  resources :sessions, only: [:new, :create, :destroy]

  root to: 'microposts#index'

  get 'products/:id' => 'catalog#view'

  match '/register', to: 'users#new', via: 'get'
  match '/users/:id/edit-avatar', to: 'users#edit_avatar', via: 'get', as: :edit_avatar
  
  match '/tags/:tag', to: 'microposts#show_in_tag', via: 'get', as: :show_in_tag

  match '/upload',  to: 'photos#new', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true, counter_cache: true
  

  validates :user_id, presence: true
  default_scope -> { order('created_at DESC') }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create, :destroy]
  before_action :correct_user, only: :destroy

  def index
    @comments = current_user.comments.all
  end

  def new
    @comment = Comment.new
  end

  def create
    resource, id = request.path.split('/')[1, 2]
 
    @commentable = resource.singularize.classify.constantize.find(id)
    @comment = @commentable.comments.new params.require(:comment).permit(:content).merge(user: current_user)

    receive_users = find_receivers(@comment.content)
    
    for user in receive_users
      if User.exists?(:name => user)
        u = User.find_by_name(user)
        Notification.create(user_id:u.id, content: @comment.content, sender_name: @comment.user.name, link_back:"#{resource}/#{id}" )
      end
    end

    if @comment.save
      redirect_to @commentable, success: '评论成功'
    else
      render :new
    end
  end
  
  def destroy
    if @comment.destroy
      redirect_to comments_url, success: '评论删除成功'
    else
      redirect_to comments_url, alert: '评论删除失败'
    end
  end
  


  private
    def comment_params
      params.require(:comment).permit(:content, :user_id, :commentable_id)
    end



    def correct_user
      @comment = current_user.comments.find_by(id: params[:id])
      redirect_to root_url if @comment.nil?
    end


end

app/helpers/comments_helper.rb
module CommentsHelper
  
end

app/views/comments/_form.html.erb
<div class="comment_form">
  <%= form_for([@micropost, @micropost.comments.build]) do |f| %>
    <div class="form-group">
      <%= f.label :content, '写个评论:' %><br>

      <%= f.text_area :content, :class => "form-control", :value => writed_comments %>
      <%# call from session_helper %>
      <% delete_writed_comments %>
    </div>
  
    <div class="actions">
      <%= f.submit '提交评论', :class => "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/comments/index.html.erb
<h1>所有评论</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Content</th>
      <th>Commentable</th>
      <th>Commentable type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.commentable_id %></td>
        <td><%= comment.commentable_type %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>