config/routes.rb
Rails.application.routes.draw do



  resources :users

  resources :microposts do
    resources :comments
  end
  resources :notifications

  resources :photos do
    resources :comments
  end

  resources :comments

  resources :sessions, only: [:new, :create, :destroy]

  root to: 'microposts#index'

  get 'products/:id' => 'catalog#view'

  match '/register', to: 'users#new', via: 'get'
  match '/users/:id/edit-avatar', to: 'users#edit_avatar', via: 'get', as: :edit_avatar
  
  match '/tags/:tag', to: 'microposts#show_in_tag', via: 'get', as: :show_in_tag

  match '/upload',  to: 'photos#new', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :name, uniqueness: { case_sensitive: false }, format: { with: /[a-zA-Z][a-zA-Z0-9]{3,19}/ }
  validates :email, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[a-z0-9-]+\.)+[a-z]{2,})\z/i }
  validates :password, length: { minimum: 6 }, :on => :create

  before_save { self.email = email.downcase }
  before_create :create_remember_token
  has_secure_password

  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  mount_uploader :avatar, AvatarUploader
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_avatar

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def crop_avatar
    avatar.recreate_versions! if crop_x.present?
  end


  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:show, :edit, :update]
  before_action :set_user, only: [:show, :edit, :edit_avatar, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_require, only: [:index, :destroy]


  def index
    @users = User.all
  end

  def show

  end


  def new
    @user = User.new
  end


  def edit
  end


  def create
    @user = User.new(user_params)

    if @user.save
      sign_in @user
      if params[:user][:avatar].present?
        render :edit_avatar
      else
        flash[:success] = "注册成功！"
        redirect_to @user
      end
    else
      render :new
    end
  end


  def update

    if @user.update_attributes(user_params)
      if params[:user][:avatar].present?
        render :edit_avatar
      else
        flash[:success] = "修改成功！"
        redirect_to @user
      end
    else
      flash[:danger] = "修改失败！"
      render :edit
    end
  end





  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, success: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:avatar, :name, :email, :password, :password_confirmation, :crop_x, :crop_y, :crop_w, :crop_h)
    end

    def signed_in_user
      redirect_to login_url, danger: "Please sign in." unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end  
end

app/helpers/users_helper.rb
module UsersHelper
  def alertWrongUserForm(obj)
    wrong = "form-control input_short alert alert-danger"
    @user.errors.each do |attr, mesg|
      if attr == obj
        return wrong
      end
    end
    normal = "form-control input_short"
  end
end

app/views/users/_form.html.erb
<div class="my_form">
  <%= form_for @user, :html => {:multipart => true} do |f| %>
    <%= f.label '头像图片'%>
    <%= f.file_field :avatar %><br>

    <%= f.label "用户名" %>
    <%= f.text_field :name, class: alertWrongUserForm(:name) %><br>

    <%= f.label "邮箱地址" %>
    <%= f.text_field :email, class: alertWrongUserForm(:email) %><br>

    <%= f.label :password, "输入密码" %>
    <%= f.password_field :password, class: alertWrongUserForm(:password) %><br>

    <%= f.label :password, "再次输入密码" %>
    <%= f.password_field :password_confirmation, class: alertWrongUserForm(:password) %><br>

    <%= f.submit "注册用户", class: "btn btn-large btn-primary"%><br>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="center pad">
<%= render "layouts/flash", object: @user %>
  <h1>修改个人资料</h1>
  <% if !@user.avatar.blank? %>
    <%= image_tag @user.avatar_url(:small).to_s %>
    <%= link_to '重新剪切头像', edit_avatar_path %>
  <% end %>
<br>
<br>

  <%= form_for @user, :html => {:multipart => true} do |f| %>
    <%= f.label '上传新头像'%>
    <%= f.file_field :avatar %><br>

    <%= f.label "用户名" %>
    <%= f.text_field :name, class:'form-control input_short' %><br>

    <%= f.label "邮箱地址" %>
    <%= f.text_field :email, class:'form-control input_short' %><br>

    <%= f.label :password, "输入密码" %>
    <%= f.password_field :password, class:'form-control input_short' %><br>

    <%= f.label :password, "再次输入密码" %>
    <%= f.password_field :password_confirmation, class:'form-control input_short' %><br>

    <%= f.submit "保存", class: "btn btn-large btn-primary"%><br>

  <% end %>

  
  <%= link_to '查看资料', @user %> |
  <%= link_to '返回主页', root_url %>
</div>

app/views/users/edit_avatar.html.erb
<style>
    .eg-container {
      padding-top: 15px;
      padding-bottom: 15px;
    }

    .eg-main {
      max-height: 525px;
      margin-bottom: 30px;
    }

    .eg-wrapper {
      background-color: #f7f7f7;
      border: 1px solid #eee;
      box-shadow: inset 0 0 3px #f7f7f7;
      height: 525px;
      width: 100%;
      overflow: hidden;
    }

    .eg-wrapper img {
      width: 100%;
    }

    .eg-preview {
      margin-bottom: 15px;
    }

    .preview {
      float: left;
      margin-right: 15px;
      margin-bottom: 15px;
      overflow: hidden;
      background: #f7f7f7;
    }

    .preview-lg {
      width: 240px;
      height: 240px;
    }

    .preview-md {
      width: 135px;
      height: 135px;
    }

    .preview-sm {
      width: 48px;
      height: 48px;
    }

    .eg-data {
      padding-right: 15px;
    }

    .eg-data .input-group {
      width: 100%;
      margin-bottom: 15px;
    }

    .eg-data .input-group-addon {
      min-width: 65px;
    }

    .eg-button > .btn {
      margin-right: 15px;
      margin-bottom: 15px;
    }

    .eg-input .input-group {
      margin-bottom: 15px;
    }

    .eg-output .btn {
      margin-right: 15px;
      margin-bottom: 15px;
    }

    .eg-output img {
      max-height: 214px;
    }
  </style>
  <div class="container-fluid eg-container" id="basic-example">
    <div class="row eg-main">
      <div class="col-xs-12 col-sm-9">
        <div class="eg-wrapper">
          <%= image_tag @user.avatar_url(:not_edit).to_s, class:"cropper" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-3">
        <div class="eg-preview clearfix">
          <div class="preview preview-lg"></div>
          <div class="preview preview-md"></div>
          <div class="preview preview-sm"></div>

        </div>
        <div class="eg-data">
          <%= form_for @user do |f| %>

            <%= f.hidden_field :crop_x, :id =>'dataX'  %>
            <%= f.hidden_field :crop_y, :id =>'dataY'  %>
            <%= f.hidden_field :crop_w, :id =>'dataWidth'  %>
            <%= f.hidden_field :crop_h, :id =>'dataHeight'  %>
            
            <%= f.hidden_field :name, class:'form-control input_short' %>
            <%= f.hidden_field :email, class:'form-control input_short' %>
            
            <%= f.submit "剪切 !", class: "btn btn-large btn-primary"%>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <%= link_to '取消', @user, class:'btn btn-danger' %><br>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<script>
  $(function() {
      var $cropper = $(".cropper"),
          $dataX = $("#dataX"),
          $dataY = $("#dataY"),
          $dataHeight = $("#dataHeight"),
          $dataWidth = $("#dataWidth"),
          $dataRotate = $("#dataRotate"),
          console = window.console || {log:$.noop},
          cropper;

      $cropper.cropper({
        aspectRatio: 9 / 9,
        data: {
          x: 90,
          y: 90,
          width: 240,
          height: 240
        },
        preview: ".preview",

        // autoCrop: false,
        // dragCrop: false,
        // modal: false,
        // moveable: false,
        // resizeable: false,
        // scalable: false,

        // maxWidth: 480,
        // maxHeight: 270,
        // minWidth: 160,
        // minHeight: 90,

        done: function(data) {
          $dataX.val(data.x);
          $dataY.val(data.y);
          $dataHeight.val(data.height);
          $dataWidth.val(data.width);
          $dataRotate.val(data.rotate);
        },
        
      });

    });
  </script>

app/views/users/index.html.erb
<h1>所有用户</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="center pad">
<%= render "layouts/flash", object: @user %>
  <h1>注册新账户</h1>

  <%= render 'form' %>

</div>

app/views/users/show.html.erb
<div class="center pad">
<%= render "layouts/flash", object: @user %>
<br>

  <h1>用户资料</h1>

<br>

  <%=link_to image_tag(@user.avatar_url(:big).to_s), edit_avatar_path %>

<br>
<br>
<br>

  <strong>名字:</strong>
  <%= @user.name %>

<br>
<br>

  <p>
    <strong>电子邮箱:</strong>
    <%= @user.email %>
  </p>

<br>

  <%= link_to '修改资料', edit_user_path(@user) if current_user == @user%> | 
  <%= link_to '返回主页', root_url %>

</div>