config/routes.rb
Rails.application.routes.draw do



  resources :users

  resources :microposts do
    resources :comments
  end
  resources :notifications

  resources :photos do
    resources :comments
  end

  resources :comments

  resources :sessions, only: [:new, :create, :destroy]

  root to: 'microposts#index'

  get 'products/:id' => 'catalog#view'

  match '/register', to: 'users#new', via: 'get'
  match '/users/:id/edit-avatar', to: 'users#edit_avatar', via: 'get', as: :edit_avatar
  
  match '/tags/:tag', to: 'microposts#show_in_tag', via: 'get', as: :show_in_tag

  match '/upload',  to: 'photos#new', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  has_many :comments,:as => :commentable, dependent: :destroy
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

  before_action :set_micropost, only: [:show, :edit, :update, :destroy]
  before_action :admin_require, only: [:new, :create, :edit, :update, :destroy]
  def index
    @microposts = Micropost.paginate(page: params[:page]).per_page(15)
    @isadmin = admin?
  end


  def show
    @micropost = Micropost.find(params[:id])
    @comments = @micropost.comments.includes(:user).all
    @comment = Comment.new
  end

  def show_in_tag
    @tag = params[:tag].gsub(/\A\s+|\s+\z/, '')
    @microposts = Micropost.where(tag: @tag).paginate(page: params[:page]).per_page(15)
  end


  def new
    @micropost = Micropost.new
    @frequent_posts = Micropost.select("tag").limit(30).uniq
  end


  def edit
    @frequent_posts = Micropost.select("tag").limit(30).uniq
  end


  def create
    @micropost = Micropost.new(micropost_params)
    @micropost.tag.gsub!(/\A\s+|\s+\z/, '')
    if @micropost.save
      flash[:success] = '微博发送成功'
      redirect_to @micropost
    else
      flash.now[:danger] = '微博发送失败'
      render 'new'
    end
  end


  def update
    if @micropost.update(micropost_params)
      flash[:success] = '微博修改成功'
      redirect_to @micropost
    else
      flash.now[:danger] = '微博修改失败'
      render 'new'
    end
  end


  def destroy
    if @micropost.destroy
      redirect_to microposts_url
    end
  end

  private
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    def micropost_params
      params.require(:micropost).permit(:content, :user_id, :tag)
    end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
  #def current_micropost
  #  micropost_id = params[:id]
  #end
end

app/views/microposts/_form.html.erb
<div class="row">
  <div class="micropost_form">
    <%= form_for(@micropost, class:"form-horizontal")  do |f|%>
      <div class="form-group">
        <%= f.label :content, "微博内容" %><br>
        <%= f.text_area :content, :class => "form-control"%><br>

        <%= f.label :content, "标签" %>

        <%= f.text_field :tag, class:'form-control input_short' %>
      </div>
      <div class="frequent-tags">
        <% @frequent_posts.each do |post| %>
          <% unless post.tag.blank? %>
            <span class="frequent-tag"><%=post.tag%></span>
          <% end %>
        <% end %>
      </div>
<br>
      <div class="actions">
        <%= f.submit "发 送", :class => "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/microposts/_micropost.html.erb
<div class="panel panel-default">
  <% count = micropost.comments_count %>
  <div class="panel-body <%= 'popular' if count > 5 %>">
    <%= raw micropost.content %>
  </div>
  <div class="panel-footer <%= 'popular' if count > 5 %>">
    <% unless  micropost.tag.blank? %>
      <ul class="pull-left tag">
        <li><i class='fa fa-tag'></i> <%=link_to micropost.tag, show_in_tag_path(micropost.tag) %></li>
      </ul>
    <% end %>
    <ul>
      <% if @isadmin %>
        <li>
          <%= link_to "修改", edit_micropost_path(micropost) %>
        </li>
        <li>
          <%= link_to '删除', micropost, method: :delete, data: { confirm: 'Are you sure?' } %>
        </li>
      <% end %>
      <li data-toggle="tooltip" data-placement="bottom" title="查看评论">
        <%= link_to content_tag(:i, " 评论 #{count}", :class => "fa fa-comments"), micropost_path(micropost), class:"link-to-comment" %>
      </li>
      <li>
        <%= time_ago_in_words(micropost.created_at) %>
      </li>
    </ul>
  </div>
</div>

app/views/microposts/edit.html.erb
<div class="center pad">
<h1>修改微博</h1>

<%= render 'form' %>
<br>
<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>
</div>

app/views/microposts/index.html.erb
<div class="container index-hold">

  <div class="row" id="content">
    <%= render @microposts %>
  </div>
  <div align="center">
    <%= will_paginate @microposts %>
  </div>

</div>

app/views/microposts/index.js.erb
$('#content').append('<%= j render(@microposts) %>');
<% if @microposts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@micropost) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/microposts/new.html.erb
<div class="center pad">
<%= render "layouts/flash", object: @micropost %>
<h1>新微博</h1>

<%= render 'form' %>

<br>

<%= link_to 'Back', microposts_path %>
</div>

app/views/microposts/show.html.erb
<div class="pad">
<%= render 'layouts/flash',object: @micropost%>
  <div class="micropost_content">
    <%= raw @micropost.content %>
  </div>
  <% unless @micropost.tag.blank? %>
    <span id='tag-in-show'><%= @micropost.tag %></span>
  <% end %>
</div>
<div class="pad">
    <% @comments.each do |comment| %>
      <div class="comment_card">
        <%= image_tag comment.user.avatar_url(:small).to_s, class:"avatar" %>
        <div class="text">
          <strong><%= link_to "#{comment.user.name}", comment.user %></strong> 
          <div class="comment-content"><%= sanitize comment.content %></div>
        </div>
      </div>
      <div class="divider"></div>
    <% end %>
  </div>
</div>
<div class="pad">
  <%= render 'comments/form' %>
</div>

app/views/microposts/show_in_tag.html.erb
<div class="container index-hold">
<h2>所有标签为 <%= @tag %> 的微博</h2>
  <div class="row" id="content">
    <%= render @microposts %>
  </div>
  <div align="center">
    <%= will_paginate @microposts %>
  </div>

</div>