config/routes.rb
Rails.application.routes.draw do



  resources :users

  resources :microposts do
    resources :comments
  end
  resources :notifications

  resources :photos do
    resources :comments
  end

  resources :comments

  resources :sessions, only: [:new, :create, :destroy]

  root to: 'microposts#index'

  get 'products/:id' => 'catalog#view'

  match '/register', to: 'users#new', via: 'get'
  match '/users/:id/edit-avatar', to: 'users#edit_avatar', via: 'get', as: :edit_avatar
  
  match '/tags/:tag', to: 'microposts#show_in_tag', via: 'get', as: :show_in_tag

  match '/upload',  to: 'photos#new', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/views/layouts/_admin_header.html.erb
<li class="dropdown">
  <% unread_num = current_user.notifications.unread.count %>

  <a class="dropdown-toggle" href="#" data-toggle="dropdown" data-no-turbolink="true">
    管理员
      <% if unread_num > 0 %>
        <span class="badge"><%= unread_num %></span>
      <% end %>
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li><%= link_to current_user.name, user_path(current_user) %></li>
    <li><%= link_to "设置", edit_user_path(current_user) %></li>
    <li><%= link_to "新微博", new_micropost_path %></li>
    <li><%= link_to "新照片", new_photo_path %></li>
    <li class="divider"></li>

    <li>
      <%= link_to notifications_url do %>
        通知&nbsp;&nbsp;&nbsp;
        <% if unread_num > 0 %>
          <span class="badge pull-rught">&nbsp;<%= unread_num %>&nbsp;</span>
        <% end %>
      <% end %>
    </li>

    <li class="divider"></li>
    <li><%= link_to "退出登录", signout_path, method: "delete" %></li>
  </ul>
</li>

app/views/layouts/_flash.html.erb
<% if flash[:success] %>
  <div class="alert alert-success" role="alert"><%= flash[:success] %></div>
<% end %>

<% if flash[:info] %>
  <div class="alert alert-info" role="alert"><%= flash[:info] %></div>
<% end %>

<% if flash[:warning] %>
  <div class="alert alert-warning" role="alert"><%= flash[:warning] %></div>
<% end %>

<% if flash[:danger] %>
  <div class="alert alert-danger" role="alert"><%= flash[:danger] %></div>
<% end %>

<% if object.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <% object.errors.full_messages.each do |message| %>
      <%= message %><br>
    <% end %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55877017-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-header">
        <i class="fa fa-bars fa-lg"></i>
        
      </button>
      <a class="navbar-brand" >Although's</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse-header">
      <ul class="nav navbar-nav">
        <li  class="<%= 'active' if params[:controller] == 'microposts' %>"><a href="/microposts">微博</a></li>
        <li class="<%= 'active' if params[:controller] == 'photos' %>"><a href="/photos">相册</i></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !signed_in? %>
          <li>
            <%= link_to content_tag(:i, " 登录", :class => "fa fa-users"), login_url %>
          </li>
        <% elsif !admin? %>
          <%= render 'layouts/normal_user_header' %>
        <% else %>
          <%= render 'layouts/admin_header' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
</header>

app/views/layouts/_normal_user_header.html.erb
<li class="dropdown">
  <% unread_num = current_user.notifications.unread.count %>
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-no-turbolink="true">
    我的账户
      <% if unread_num > 0 %>
        <span class="badge"><%= unread_num %></span>
      <% end %>
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to current_user.name, user_path(current_user) %></li>
    <li><%= link_to "设置", edit_user_path(current_user) %></li>

    <li>
      <%= link_to notifications_url do %>
        通知&nbsp;&nbsp;&nbsp;
        <% if unread_num > 0 %>
          <span class="badge pull-rught">&nbsp;<%= unread_num %>&nbsp;</span>
        <% end %>
      <% end %>
    </li>
    <li class="divider"></li>
    <li><%= link_to "退出登录", signout_path, method: "delete" %></li>
  </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Although's Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<%= render 'layouts/header'%>
<%= yield %>
<%= render 'layouts/footer'%>
</body>
</html>